config:
  agent:
    interval: "10s"
    round_interval: true
    metric_buffer_limit: 10000
    flush_buffer_when_full: true
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
    debug: false
    quiet: false
    hostname: ""
  outputs:
    - influxdb:
        urls: ["http://influxdb:8086"] # required
        database: "telegraf" # required
        precision: "s"
        timeout: "5s"
  
  inputs:
    - kafka_consumer:
        name_override: "turbofan_prediction"
        brokers: 
          - "kafka:9092"
        topics: 
          - "turbofan_prediction"
        data_format: "json"
        tag_keys: 
            - "device"
        consumer_group: "telegraf"
    - http:
      name_override: "turbofan_prediction_stats"
      urls: ["http://prediction-deployment:6066/stats/"]
      data_format: "json"
      json_query: [ "Sensor0.events_total", "Sensor0.events_active", "Sensor0.events_s", "Sensor0.events_runtime_avg"]

