Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "cloud3"
  config.vm.network "public_network", ip: "192.168.1.137"
  config.vm.network "private_network", ip: "192.168.2.2"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
